package main

var thirdPartyModules = []string{
	"7z.dll",
	"7za.exe",
	"AutoMapper.*.dll",
	"Castle.Core.*",
	"Castle.Windsor.*",
	"componentspace.saml2.dll",
	"devexpress.*",
	"entityframework.dll",
	"gradle-wrapper.jar",
	"itextsharp.dll",
	"log4net.dll",
	"microsoft.*.dll",
	"microsoft.*.pdb",
	"newrelic.*.dll",
	"newtonsoft.json.*",
	"ninject.web.common.webhost.dll",
	"org.eclipse.*.jar",
	"syncfusion.*",
	"system.*.dll",
	"Telerik.*.dll",
	"WebGrease.dll",
}
